---
- hosts: all
  #remote_user: root
  #become: yes
 # become_method: su

  tasks:
  - name: Install Apache
    yum: pkg=httpd state=latest
  - name: Copying the demo file
    - name: Place the index file at project
      copy:
         src: /etc/ansible/index.html
         dest: /var/www/html/
         owner: apache
         group: apache
         mode: 0644
  - name: Enable Apache on System Boot
    service: name=httpd enabled=yes

    notify:
    - start apache
  
  handlers:
    - name: start apache
      service: name=httpd state=started
