---
- hosts: all
# use priviledge (default : root)
  become: yes
# the way to use priviledge
  become_method: sudo
# define tasks
  tasks:
  - name: httpd is installed
    yum: name=httpd state=present
  - name: Copies template
    copy:
       src: /etc/ansible/index.html
       dest: /var/www/html
       owner: apache
       group: apache
       mode: 0755
 
