---
- name: apache installation
  yum: name={{ item }} state=present
  with_items:
     - httpd
     - httpd-tools
- name: copy files
  copy: src=index.html dest=/var/www/html/index.html
  tags: http
  notify: restart httpd service
